#include QMK_KEYBOARD_H

enum layer_names {
    _QW,
    _RS,
    _LW,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [_QW] = LAYOUT(
      KC_Q,
      KC_W,
      KC_E,
      KC_R,
      KC_T,
      KC_Y,
      KC_U,
      KC_I,
      KC_O,
      KC_P,
      KC_A,
      KC_S,
      KC_D,
      KC_F,
      KC_G,
      KC_H,
      KC_J,
      KC_K,
      KC_L,
      KC_SCLN,
      LSFT_T(KC_Z),
      KC_X,
      KC_C,
      KC_V,
      KC_B,
      KC_GRV,
      KC_BSLS,
      KC_N,
      KC_M,
      KC_COMM,
      KC_DOT,
      KC_SLSH,
      MO(_RS),
      KC_TAB,
      KC_LCTL,
      KC_LGUI,
      KC_BSPC,
      KC_ESC,
      KC_LSFT,
      KC_SPC,
      KC_RALT,
      KC_MINS,
      KC_QUOT,
      KC_ENT
    ),
    [_RS] = LAYOUT(
      KC_1,
      KC_2,
      KC_3,
      KC_4,
      KC_5,
      KC_6,
      KC_7,
      KC_8,
      KC_9,
      KC_0,
      KC_TAB,
      KC_MPRV,
      KC_MPLY,
      KC_MNXT,
      KC_NO,
      KC_LEFT,
      KC_DOWN,
      KC_UP,
      KC_RGHT,
      KC_EQL,
      KC_LSFT,
      KC_VOLD,
      KC_MUTE,
      KC_VOLU,
      KC_NO,
      KC_WH_D,
      KC_NO,
      KC_LBRC,
      KC_RBRC,
      KC_LCBR,
      KC_RCBR,
      KC_NO,
      KC_NO,
      KC_NO,
      KC_NO,
      KC_NO,
      KC_DEL,
      KC_WH_U,
      TG(_LW),
      RAG(KC_C),
      RAG(KC_F),
      KC_NO,
      KC_NO,
      KC_NO
    ),
    [_LW] = LAYOUT( /* [> LOWER <] */
    KC_INS,  KC_HOME, KC_UP,   KC_END,  KC_PGUP,                   KC_UP,   KC_F7,   KC_F8,   KC_F9,   KC_F10  ,
    KC_DEL,  KC_LEFT, KC_DOWN, KC_RGHT, KC_PGDN,                   KC_DOWN, KC_F4,   KC_F5,   KC_F6,   KC_F11  ,
    KC_NO,   KC_VOLU, KC_NO,   KC_NO,   RESET,   _______, _______, KC_NO,   KC_F1,   KC_F2,   KC_F3,   KC_F12  ,
    KC_NO,   KC_VOLD, KC_LGUI, KC_LSFT, KC_BSPC, KC_LCTL, KC_LALT, KC_SPC,  TO(_QW), KC_PSCR, KC_SLCK, KC_PAUS )
};
